language: go
go:
  - 1.5.3
env:
  - VER=4.1
before_install:
  - sudo apt-get update
  - sudo apt-get install apt-transport-https
  - curl -s https://repo.varnish-cache.org/ubuntu/GPG-key.txt |
    sudo apt-key add -
  - echo "deb https://repo.varnish-cache.org/ubuntu/ precise varnish-$VER" |
    sudo tee /etc/apt/sources.list.d/varnish-cache.list
  - sudo apt-get update
  - sudo apt-get install varnish libvarnishapi-dev
  - sudo usermod -a -G varnish $USER
script: sudo -E su $USER -c 'go test -v'
